name: Stories by WegnerDesign
description: "Short Stories, by a nerd."
url: http://stories.wegnerdesign.com
safe: true
lsi: false
pygments: true
paginate: 10
auto: true
markdown: redcarpet
permalink: /:title
